name: Publish go server to GitHub Container Registry

on:
  push:
    branches:
      - 'main'
    paths:
      - "golang/**"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    working-directory: .golang/
    steps:
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: 1.19
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

      - uses: imjasonh/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6
      - run: ko build . --platform=linux/amd64,linux/arm64 -B

